language: java
jdk:
  - openjdk8
notification:
  email:
    recipients:
      - sandisks555@gmail.com
    on_success: change
    on_failure: always

before_install:
  - pip install --user codecov

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - echo "MAVEN_OPTS='-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m'" > ~/.mavenrc

script:
  - mvn clean test jacoco:report
  - ls
  - pwd

after_success:
  - codecov

branches:
  only:
    - master

env:
  global:
    - "MAVEN_OPTS=-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m"

cache:
  directories:
    - $HOME/.m2
